"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."

"preserve_hierarchy": true

"files": [
  {
    source: "/src/assets/i18n/en-GB.json",
    translation: "/src/assets/i18n/%locale%.json"
  }
]
