name: Crowdin Download Action

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write

jobs:
  crowdin-download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history

      - name: Set branch name
        run: echo "BRANCH_NAME=l10n_crowdin_translations" >> $GITHUB_ENV

      - name: Commit pre-existing changes (if any)
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git diff --cached --quiet || git commit -m "Preemptive commit before checkout"

      - name: Check if branch exists
        id: check-branch
        run: |
          if git ls-remote --exit-code --heads origin $BRANCH_NAME; then
            echo "Branch exists, checking it out."
            git checkout $BRANCH_NAME
            git pull origin $BRANCH_NAME
            echo "EXISTING_BRANCH=true" >> $GITHUB_ENV
          else
            echo "Branch does not exist, creating a new one."
            git checkout -b $BRANCH_NAME
            echo "EXISTING_BRANCH=false" >> $GITHUB_ENV
          fi

      - name: Synchronize with Crowdin
        uses: crowdin/github-action@v2
        with:
          upload_sources: false
          upload_translations: false
          download_translations: true
          localization_branch_name: ${{ env.BRANCH_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      - name: Commit new translations
        run: |
          git add .
          git diff --cached --quiet || git commit -m "Update translations from Crowdin"

      - name: Push changes
        run: git push origin $BRANCH_NAME

      - name: Create Pull Request (if not exists)
        if: env.EXISTING_BRANCH == 'false'
        uses: peter-evans/create-pull-request@v5
        with:
          branch: ${{ env.BRANCH_NAME }}
          title: 'New Crowdin translations'
          body: 'New Crowdin pull request with translations'
          base: 'main'
          delete-branch: false
          token: ${{ secrets.GH_TOKEN }}
