name: Crowdin Download Action

on:
  schedule:
    - cron: '* * * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  crowdin-download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures full history is available

      - name: Ensure no uncommitted changes before branch checkout
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "Uncommitted changes detected. Stashing them before proceeding."
            git stash
          fi

      - name: Synchronize with Crowdin
        uses: crowdin/github-action@v2
        with:
          upload_sources: false
          upload_translations: false
          download_translations: true
          localization_branch_name: "l10n_crowdin_translations"
          create_pull_request: true
          pull_request_title: 'New Crowdin translations'
          pull_request_body: 'New Crowdin pull request with translations'
          pull_request_base_branch_name: 'main'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
