name: Crowdin Action

on:
  push:
    branches: [ main ]

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0  # Ensure full history for merging

      - name: Configure Git Authentication with PAT
        run: |
          git config --global url."https://${{ secrets.GH_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Crowdin Sync
        uses: crowdin/github-action@v2
        with:
          upload_sources: true
          upload_translations: true
          download_translations: true
          localization_branch_name: l18n_main
          create_pull_request: false  # Disable automatic PR creation
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      - name: Commit and Push Changes Separately
        run: |
          git fetch origin l18n_main || git branch l18n_main
          git checkout l18n_main

          # Ensure branch is up to date to avoid conflicts
          git reset --hard origin/l18n_main || echo "Branch does not exist remotely"
          git merge --no-edit main

          git add -A

          # Commit only if there are changes
          git diff --cached --quiet || git commit -m "Update translations"

          git push origin l18n_main

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: l18n_main
          destination_branch: main
          pr_title: 'New Crowdin Translations'
          pr_body: 'New Crowdin translations by [Crowdin GH Action](https://github.com/crowdin/github-action)'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Debug Git State (if failure occurs)
        if: failure()
        run: |
          git status
          git log --oneline -5
          git branch -vv
          ls -lah .git/objects
